### ISSUE TITLE
Multiple Locators

### ISSUE THREAD

**Issue by yozaner1324** [gemfire/gemfire-testcontainers#1]
### Is your feature request related to a problem? Please describe.

Some of our tests use multiple locators

### Describe the solution you'd like

Add the ability to specify number of locators as well as servers.

**Comment by jdeppe-pivotal** [comment]
WIth the latest `2.0.0` version, multiple locators can be specified when constructing the cluster:
```
GemFireCluster dockerCluster = new GemFireCluster(2, 3);
```
Would create a cluster with `2` locators and `3` servers.
