### ISSUE TITLE
Be able to get Server Ports

### ISSUE THREAD

**Issue by yozaner1324** [gemfire/gemfire-testcontainers#2]
### Is your feature request related to a problem? Please describe.

Some tests use pools or other features that require knowing the server ports

### Describe the solution you'd like

Add some way to retrieve the server ports like you can for the locator.

**Comment by jdeppe-pivotal** [comment]
WIth the latest 2.0.0 version, server ports can be retrieved with:
```
getServerPorts()
```
The returned list is indexed corresponding to the server member's name. Thus index `0` corresponds to `server-0`, index `1` to `server-1`, etc.
