### ISSUE TITLE
Specifying withCopyFileToContainer should copy the files to all members before start

### ISSUE THREAD

**Issue by yozaner1324** [gemfire/gemfire-testcontainers#3]
### Is your feature request related to a problem? Please describe.

To configure SSL, the trusted.keystore needs to be available on the locator and all servers before they are started. 

### Describe the solution you'd like

Make sure than withCopyFileToContainer copies files before starting the member and that it copies to all containers, not just the locator as it does now.

**Comment by jdeppe-pivotal** [comment]
WIth the latest `2.0.0` version, files can be copied with:
```
withPreStart(ALL_GLOB, x -> x.copyFileToContainer(Transferable.of(keystoreBytes), "/keystore.jks"))
```
